import { Search, PenTool, Code2, ShieldCheck, Rocket } from "lucide-react";
import type { Phase } from "@/types";

export const PHASES: Phase[] = [
  {
    label: "01  Discovery",
    short: "Discovery",
    eyebrow: "discovery",
    icon: Search,
    title: "Signed scope in 2 days.",
    deliverables: [
      "Precise scope document",
      "Risk register with mitigations",
      "Fixed-cost estimate — no ambiguity",
    ],
    traditional: "2–3 weeks",
    tBar: 80,
    withLyrnique: "2 days",
    lBar: 16,
  },
  {
    label: "02  Design",
    short: "Design",
    eyebrow: "design",
    icon: PenTool,
    title: "Dev-ready specs before code starts.",
    deliverables: [
      "System architecture diagram",
      "UI component map",
      "API contracts documented",
    ],
    traditional: "1–2 weeks",
    tBar: 68,
    withLyrnique: "48 hours",
    lBar: 20,
  },
  {
    label: "03  Build",
    short: "Build",
    eyebrow: "build",
    icon: Code2,
    title: "40% faster. Zero quality trade-off.",
    deliverables: [
      "Reviewed, tested modules — weekly",
      "Typed API layer with full documentation",
      "Live demo at every milestone",
    ],
    traditional: "Standard pace",
    tBar: 100,
    withLyrnique: "40% faster",
    lBar: 60,
  },
  {
    label: "04  QA",
    short: "QA",
    eyebrow: "qa",
    icon: ShieldCheck,
    title: "90%+ test coverage on handover.",
    deliverables: [
      "Comprehensive test suite",
      "Edge cases documented & covered",
      "Zero known regressions on delivery",
    ],
    traditional: "60–70% avg coverage",
    tBar: 65,
    withLyrnique: "90%+ coverage",
    lBar: 94,
  },
  {
    label: "05  Deploy",
    short: "Deploy",
    eyebrow: "deploy",
    icon: Rocket,
    title: "Code-complete to live in < 24 hours.",
    deliverables: [
      "Production deployment",
      "Monitoring & alerts active from day one",
      "Handover documentation included",
    ],
    traditional: "Days of manual ops",
    tBar: 82,
    withLyrnique: "< 24 hours",
    lBar: 14,
  },
];
